-- only for development
DROP TABLE IF EXISTS Bill;
DROP TABLE IF EXISTS Treatment;
DROP TABLE IF EXISTS Appointment;
DROP TABLE IF EXISTS Patient_Allergy;
DROP TABLE IF EXISTS Allergy;
DROP TABLE IF EXISTS Patient_Punishment;
DROP TABLE IF EXISTS Punishment;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS Blood_Type;
DROP TABLE IF EXISTS Doctor_Specialization;
DROP TABLE IF EXISTS Specialization;
DROP TABLE IF EXISTS Doctor_Schedule;
DROP TABLE IF EXISTS Schedule;
DROP TABLE IF EXISTS Doctor;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Admin;